# Generated by Django 5.1.1 on 2024-09-20 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0002_rename_bill_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Quantity',
        ),
    ]
