# Generated by Django 5.1.1 on 2024-09-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0003_remove_products_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='Product_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
