# Generated by Django 5.1.1 on 2024-09-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0005_product_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_bill',
            name='Product',
            field=models.CharField(max_length=200),
        ),
    ]
