# Generated by Django 5.1.1 on 2024-09-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0006_alter_product_bill_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_bill',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
