# Generated by Django 5.1.1 on 2024-09-20 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0007_product_bill_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_bill',
            name='price',
        ),
    ]
