# Generated by Django 5.1.1 on 2024-09-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0012_remove_product_bill_man'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_bill',
            name='Man',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
