# Generated by Django 5.1.1 on 2024-10-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0014_remove_product_bill_man'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_bill',
            name='bill_to',
            field=models.CharField(blank=True, max_length=210, null=True),
        ),
    ]
