# Generated by Django 5.1.1 on 2024-10-01 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bill', '0015_product_bill_bill_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_bill',
            name='bill_to',
        ),
    ]
